workspace:
  base: /go
  path: src/github.com/presslabs/mysql-operator

pipeline:
  dependencies:
    image: golang:1.11
    commands:
      - make dependencies

  lint:
    image: golang:1.11
    commands:
      - make lint

  test:
    image: golang:1.11
    commands:
      - make test
